
[build]
  command = "yarn build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard"
  status = 200


[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"